name: Deploy Infrastructure on DEV

on:
  push:
    branches:
      - dev
  deployment:
    types: [ created ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    container:
      image: ubuntu:18.04

    steps:
      - name: echo variables
        run: echo ${{ secrets.AWS_ACCESS_KEY_ID}} ${{ secrets.AWS_DEFAULT_REGION}}
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Install dependencies
        run: |
          apt-get clean 
          apt-get update -qq
          apt-get install -y unzip sudo
          apt-get install -y unzip
          apt-get install -y curl 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.3.6
            terraform_wrapper: true

      - name: Deploy networking infrastructure
        run: |
          cd Project/dev/network/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy security group infrastructure
        run: |
          cd Project/dev/securityGroup/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy launch template infrastructure
        run: |
          cd Project/dev/launchTemplate/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy bastion host infrastructure
        run: |
          cd Project/dev/bastionHost/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy target group infrastructure
        run: |
          cd Project/dev/targetGroup/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy application load balancer infrastructure
        run: |
          cd Project/dev/applicationLoadBalancer/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy auto scaling group infrastructure
        run: |
          cd Project/dev/autoScalingGroup/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy scaling policies infrastructure
        run: |
          cd Project/dev/scalingPolicies/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan        
    
