name: Deploy Infrastructure on DEV

on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
#        if: env == 'dev'
        run: |
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
      - name: Install dependencies
        run: |
          apt-get clean 
          apt-get update -qq
          apt-get install -y unzip
          apt-get install -y curl 
          curl -O https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
          unzip terraform_0.12.24_linux_amd64.zip
          mv terraform /usr/local/bin/
      - name: Configure AWS CLI
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set aws_session_toke $AWS_SESSION_TOKEN
            aws configure set default.region $AWS_DEFAULT_REGION
      - name: Deploy networking infrastructure
        run: |
          cd Project/dev/network/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy security group infrastructure
        run: |
          cd Project/securityGroup/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy launch template infrastructure
        run: |
          cd Project/launchTemplate/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy bastion host infrastructure
        run: |
          cd Project/bastionHost/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy target group infrastructure
        run: |
          cd Project/targetGroup/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy application load balancer infrastructure
        run: |
          cd Project/applicationLoadBalancer/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy auto scaling group infrastructure
        run: |
          cd Project/autoScalingGroup/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan
      - name: Deploy scaling policies infrastructure
        run: |
          cd Project/scalingPolicies/
          terraform init
          terraform plan -out=tfplan
          terraform apply tfplan        
    
