name: Trivy
on:
  push:
    branches: [ "dev","staging", "prod" ]
  pull_request:
    branches: [ "dev","staging","prod" ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          format: 'sarif'
          output: 'trivy-results.sarif'



      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
